version: "3.9"

services:
  frontend:
    image: saqlainmustafa/frontend:latest
    ports:
      - "3000:3000"
    environment:
      - API_HOST=http://backend:8000
    depends_on:
      - backend

  backend:
    image: saqlainmustafa/backend:latest
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo/nutristrat_dev
      - DB_HOST=mongo
      - DB_PORT=27017
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
